// Global Usings
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading.Tasks;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using System.Net;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
global using Microsoft.AspNetCore.Mvc;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Authorization;
global using System.Diagnostics;
global using System.Security.Claims;
global using EcomGalaxy.Domain.Models.Context;
global using EcomGalaxy.Domain.Models.Payment;
global using EcomGalaxy.Domain.Models.Product;
global using EcomGalaxy.Domain.Models.ShoppingCart;
global using EcomGalaxy.Domain.Models.User;
global using EcomGalaxy.ViewModel.User;
global using EcomGalaxy.ViewModel.ShoppingCart;
global using EcomGalaxy.ViewModel.Role;
global using EcomGalaxy.ViewModel.Review;
global using EcomGalaxy.ViewModel.Profile;
global using EcomGalaxy.ViewModel.Product;
global using EcomGalaxy.ViewModel.Order;
global using EcomGalaxy.ViewModel.Auth;
global using EcomGalaxy.Domain.Models.Order;


